%let pgm=utl-setup-personal-edition-altair-slc-eclipse-workspace-config-sasautos-sasuser-saswork-autoexec;

%stop_submission;

Setup personal edition altair slc eclipse workspace config sasautos sasuser saswork autoexec

eclipse layout
https://tinyurl.com/yvebd3ee
https://github.com/rogerjdeangelis/setup-personal-edition-altair-slc-eclipse-workspace-config-sasautos-sasuser-saswork-autoexec/blob/main/wpslayout.png


github
https://tinyurl.com/5c7kspet
https://github.com/rogerjdeangelis/setup-personal-edition-altair-slc-eclipse-workspace-config-sasautos-sasuser-saswork-autoexec

related

github
https://tinyurl.com/48f5zfwu
https://github.com/rogerjdeangelis/utl-create-sas-classic-dms-editor-for-personal-altair-analytics-workbench-eclipse-ide

Template workspce for eclipse
metadats
https://tinyurl.com/4p8yy657
https://github.com/rogerjdeangelis/utl-create-sas-classic-dms-editor-for-personal-altair-analytics-workbench-eclipse-ide/blob/main/.metadata.zip


SOAPBOX ON

This may not be entirely correct. I am new to the personal edition of the Altair SLC.
These are just my observations.
You may need to open your own program and x out of the one provided. Looking for sample program error.


PREP: see files in github

  FOLDERS
   1  C:\Program Files\Altair\SLC\2025
        altairslc.cfg see github
   2 c:/wpsoto   for autocall macros
        autoexec.sas  see github
   3 c:/wps/     for programs
   4 d:/wpsusr   for sasuser
   5 d:/wpswrk   for sas work
   6 d:/wpsa     template eclipse workspace (has the layout)
                 The location for the workspace is chosen when starting Altair SLC Workbench for the first time
     If you get switched into another workspace
      go to file>switch workspace>wpsa (or where ever you put the workspce folder)
      You might want to keep the downloaded .metadata.zip in d:/wpsa.
      Eclipse seems a little flaky and you may need to restore metadats from the zip.
      Be nice if someone would remove 80% of the eclipse functions, minimally the greyed out functions.

  FILES
   1   altairslc.cfg  C:\Program Files\Altair\SLC\2025\altairslc.cfg
   2   autoexec,sas   c:/wpsoto/autoexec.sas

CONTENTS  (I think most of these issues are related to the missing CLI)

  Workarounds below

   1 Does not support user config file
   2 Does not support user autoexec (nned to edit config file)
   3 Does not support sas options statement in autoexec
   4 requires intit macro that has to be executed before any program submission
   5 How to clear LOG, Program and List
     Clear log icon does not clear log
     Altair>clear log does not clear log
   6 How to assign editor keys to function keys and mouse actions
   7 Sample program
   8 Issue with autoexec


1. DOES NOT SUPPORT A USER CONFIG FILE
   ------------------------------------

  I had to update the config file located at C:\Program Files\Altair\SLC\2025\altairslc.cfg.
  Perhaps you should install the personal edition outside of program files.

  /* uodate with these settings */

  -WORK 'd:\wpswrk'
  -set SASAUTOS ('!wpshome\sasmacro' 'c:/wpsoto')
  -SASAUTOS (SASAUTOS)
  -AUTOEXEC 'c:/wpsoto/autoexec.sas'
  -SASUSER 'd:/wpsusr'

  /*--- -SASUSER 'd:/wpsusr' does not work? ---*/

  The  perssonal edition, unlike other editions, does no support
  an extenal config file.

2 DOES NOT SUPPORT USER AUTOEXEC (nned to update system config)
  -------------------------------------------------------------

  Also the personal edition does not support a user autoexcec file without edition system config

  This works
  -AUTOEXEC 'c:/wpsoto/autoexec.sas'

3 AUTOEXEC IGNORES OPTION STATEMENT OR INSIDE ANY MACRO
  --------------------------------------------------------
   options ls=255 ps=65  nofmterr nocenter nodate nonumber noquotelenmax validvarname=upcase
   compress=no FORMCHAR='|----|+|---+=|-/\<>*' xcmd;


3  DOES NOT SUPPORT SASUSER OPTION OUTSIDE THE SYSTEM CONFIG FILE
   --------------------------------------------------------------


4  TO TURN OF AUTOGENERATED ODS HTML AND TO SET YOUR OPTIONS.  ADD THIS TO YOUR AUTOEXEC.
   -=====================================================================================

   AUTOEXEC (SAME ISSUE AS SAS EG-AUTOGENERATED STUFF BEFORE EVERY SUBMISSION)

   %global _init_;

   %let _init_= %nrstr(
      ods html close;
      ods listing;
      options ls=255 ps=65  nofmterr nocenter nodate nonumber
      noquotelenmax validvarname=upcase
      compress=no FORMCHAR='|----|+|---+=|-/\<>*');

   THEN MAKE SURE YOU PUT &_INIT_ BEFORE ANY SUBMISSION

      &_init_; /*-- before any submission --*/

      Like

      &_init_;
      proc options;
      run;

      NOCENTER           Align listing output to the left of the page
      ODATE             Do not print the date and time at the top of

 5  HOW TO CLEAR LOG, PROGRAM AND LIST
    ----------------------------------

    Clear log icon does not clear log
    Altair>clear log does not clear log

    LISTING: To clear the 'Listing for Local Server'
    right click anywhere in the listing output and select
    Clear Results

    PROGRAM: To clear the program (two ways)
      Highlight the code and hit cntl-x (cut)
      File>new>untitled program

    LOG: COULD NOT


    If you lose the OUTPUTS in the bottom panel then
    go to upper tool bar
       windows>show view>outputs

    If you lose the log screen but have the logtab then
    grab the log tab an drag it before the program screen.

    Note you can always get  Dates output and log.
    Using the dated outputs in the lower panel.

    For  log in click on log in the right panel
    for  listing output  results to restore upper panels
    
    If you have two tabs in the LOG Screen
    LOG for LOCAL SERVER X and LOG FOR NOW X
    Clicking on the X in Log for Now will clear both logs

 6 HOW TO ASSIGN EDITOR KEYS TO FUNCTION KEYS AND MOUSE ACTIONS
   ------------------------------------------------------------

   From Altair Community

   You can define keyboard function keys to perform
    specific tasks in the workbench by using the following steps:

   1. Goto Windows->Preferences->General->Keys
   2. In the ‘type filter text’ at the top enter Run SAS and you should
      see the current binding for running a SAS program (usually Ctrl^R)
   3. Go down to the Binding: input line at the bottom and highlight
      the current entry
   4. Now press the function key you would like to define, such as the
      F5 key. The definition F5 should replace Ctrl^R.
      When you enter OK to the form you should be able to run any SAS language
      program from the currently highlighted tab in the workbench by pressing the F5 key.

   TO assigb F5 to the middle mouse
     Here is how to do it with the Logitech G502 Hero Mouse

     Go to Assignments option and drag and drop
     F5 to middle click on then mouse picture

  7 SAMPLE PROGRAM
    --------------

    Macro variable _init_ is creae in the autoexec file

    %global _init_;

    %let _init_= %nrstr(ods html close;ods listing;
    options ls=255 ps=65  nofmterr nocenter nodate nonumber noquotelenmax validvarname=upcase
    compress=no FORMCHAR='|----|+|---+=|-/\<>*');

    file>new>untitled program

     &_init_;
     data test;
      do x=1 to 10;
       y=x*82;
       output;
      end;
     run;quit;

     proc print data=test;
     run;quit;

  8 ISSUE WITH AUTOEXEC
    -------------------

    Some junk is inserted before the auto exec

    NOTE: AUTOEXEC processing beginning; file is c:\wpsoto\autoexec.sas
    NOTE: AUTOEXEC source line
    1       +  ï»¿
           ^
    ERROR: Expected a statement keyword : found "ï"

     "xxxx options ls=255 ps=65  nofmterr nocenter nodate nonumber noquotelenmax validvarname=upcase
     compress=no FORMCHAR='|----|+|---+=|-/\<>*' xxxx"
     NOTE: Library wpsuser assigned as follows:


SOAPBOX OFF
